#! /bin/sh

/bin/mount -a

echo "
            _ _ _ _ _ _ _ _ _ _ _ _
            \  _  _   _  _ _ ___
            / /__/ \ |_/
           / __   /  -  _ ___
          / /  / /  / /
  _ _ _ _/ /  /  \_/  \_ ______
___________\___\__________________
"
for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ] ;
	then
		echo "[RCS]: $initscript"
		$initscript
	fi
done
hostname -F /etc/hostname
ifconfig eth0 192.168.117.2 up
route add default gw 192.168.117.1
cd /ko
insmod g_ether.ko
/ko/load3516ev200 -i -sensor imx307
mkdir -p /root/app
#mount -t tmpfs -o size=5M app /root/app
#tar zxf /root/app.tgz -C /root/app/
/bin/stupid-ftpd
telnetd
ifconfig usb0 192.168.137.25 up
route add default gw 192.168.137.1
#sed -i "5c bind_address = \"192.168.137.25\"" /etc/config.hcl
#/bin/mDNS --config /etc/config.hcl >/dev/null 2>&1 &
/root/display.sh 
cat /root/rgb.565 >/dev/fb0 
cd /root
/root/wifi.sh 
#/root/dopi_rtsp 
