#! /bin/sh

/bin/mount -a

echo "
            _ _ _ _ _ _ _ _ _ _ _ _
            \  _  _   _  _ _ ___
            / /__/ \ |_/
           / __   /  -  _ ___
          / /  / /  / /
  _ _ _ _/ /  /  \_/  \_ ______
___________\___\__________________
"
for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ] ;
	then
		echo "[RCS]: $initscript"
		$initscript
	fi
done
ifconfig eth0 up
udhcpc -i eth0 &
cd /ko
/ko/load3516ev200 -i -sensor imx307
mkdir -p /root/app
mount -t tmpfs -o size=5M app /root/app
tar zxf /root/app.tgz -C /root/app/
